### ISSUE TITLE
Suggestion or FR

### ISSUE THREAD

**Issue by DavidStrada** [erremauro/TwoDark#1]
I would like to see File base Icons currently I see this :

![Image of No-Icons](https://dl.dropboxusercontent.com/u/13359706/Screen%20Shot%202016-09-20%20at%201.38.58%20PM.png)

Atom app

![Image of No-Icons](https://dl.dropboxusercontent.com/u/13359706/Screen%20Shot%202016-09-20%20at%201.42.39%20PM.png)

**Comment by erremauro** [comment]
Hi David, in Sublime Text are the syntax definitions who specify their own file icon type.

TwoDark provide icons for default file icon type, but the syntax definition must provide a standard icon name  in the syntax package configuration. 

I've tried to do a fresh install of Sublime Text 3 and TwoDark correctly picks up the icon for the default syntax definitions, as you can see:

![screenshot 2016-09-21 13 14 47](https://cloud.githubusercontent.com/assets/5002907/18708891/7778aa6e-7ffd-11e6-81dd-cf46f202f9a2.png)

I think your Sublime Text installation is somewhat corrupted, you are using custom syntax definitions that doesn't provide a standard file icon type or you are not using Sublime Text 3 (file icons are only supported since version 3)

Having said that, I can see from your Atom screenshot that you've installed an additional pack with custom icon (https://github.com/DanBrooker/file-icons). Those icons are not available in TwoDark, since they are not part of the original OneDark Theme. Besides, I think a much simpler icon set avoid visual clutter and that's why I decided to go with standard icon set.

**Comment by DavidStrada** [comment]
I tried on a new ST3 installation and it works, not sure what plugin got things wrong ( ST3 ).
thanks!

**Comment by victorwpbastos** [comment]
It would be awesome if we can change the icons. Maybe with [ZZ File Icons](https://github.com/oivva/st-file-icons) integration.
